### ISSUE TITLE
Potential Bug when generating images with ECGs in .mat format.

### ISSUE THREAD

**Issue by sergiogvz** [alphanumericslab/ecg-image-kit#10]
While generating the ECG images with ECGs in .mat format, we encountered the following error:

`IndexError: Channel 6 contain values outside allowed range [-32768, 32767] for fmt 16`

After debugging the code, we concluded that there might be a bug in line [177](https://github.com/alphanumericslab/ecg-image-kit/blob/fd13a63ae451c992c6822d1a5225db894d6e6a76/codes/ecg-image-generator/helper_functions.py#L177) of function `samples_to_volts`, helper_functions.py.  

```python
def samples_to_volts(signal,adc_gain):
    signal_threshold = 10
    if(np.max(signal))>10:
        signal = signal/adc_gain
    return signal
```

The function will scale the units to volts if the signal's maximum exceeded the threshold 10. However, it doesn't consider if the signal values are considerably bellow zero due to baseline wander or distortion. Thus, the correction would be to apply the max. absolute of the signal:

```python
def samples_to_volts(signal,adc_gain):
    signal_threshold = 10
    if(np.max(np.abs(signal)))>10:
        signal = signal/adc_gain
    return signal
```

Please could you confirm whether we are right and this is a correct solution? Thank you.

Besides, line [274](https://github.com/alphanumericslab/ecg-image-kit/blob/fd13a63ae451c992c6822d1a5225db894d6e6a76/codes/ecg-image-generator/helper_functions.py#L274) of the same file should be changed from `arr[arr == np.nan] = BIT_NAN_16/adc_gn` to `arr[np.isnan(arr)] = BIT_NAN_16/adc_gn` to have any effect. However, this won't any significant effect, since wfdb.wrsamp already manages the nan as expected.

**Comment by sergiogvz** [comment]
The previous fix and pull request would only solve the problem, when using --mask_unplotted_samples. Otherwise, the code will fail with the same error `IndexError: Channel {n_channel} contain values outside allowed range [-32768, 32767] for fmt 16`. This is happening because the segments `nanArray[:] = record_dict[key][...:...]` in func `get_paper_ecg` aren't scaled. To solve this, I would suggest to scale the whole signal earlier, for example in line [74](https://github.com/alphanumericslab/ecg-image-kit/blob/fd13a63ae451c992c6822d1a5225db894d6e6a76/codes/ecg-image-generator/extract_leads.py#L74) include the following code:

```python
for gain_index, key in enumerate(record_dict.keys()):
    record_dict[key] = samples_to_volts(record_dict[key],adc[gain_index])
```

Besides, it is a bit strange to me that parts of the signal (`frame[key]`) are passed through `samples_to_volts` and `center_function` and other parts aren't (`nanArray[:]`, in case of mask_unplotted_samples=False, it is not a nan array anymore). My expectation would be that the whole signal is scaled and centered first all together, or by segments of 10 seconds.

**Comment by deepanshi-s** [comment]
Hi @sergiogvz Thank you for pointing out the issue!

We have updated the code to remove the centering function and sample to volts function.
