### ISSUE TITLE
Strange vertical lines between leads?

### ISSUE THREAD

**Issue by gpwhs** [alphanumericslab/ecg-image-kit#14]
![image](https://github.com/alphanumericslab/ecg-image-kit/assets/20056845/37608063-0143-4a8b-9238-3a96a8586c84)

Why are these vertical lines added?

seems to occur due to this code in ecg_plot.py, but I don't understand why you've done this?

`        if columns > 1 and (i + 1) % columns != 0:
            sep_x = [len(ecg[leadName]) * step + x_offset + dc_offset + x_gap] * round(8 * y_grid_dots)
            sep_x = np.array(sep_x)
            sep_y = np.linspace(y_offset - 4 * y_grid_dots * step, y_offset + 4 * y_grid_dots * step, len(sep_x))
            ax.plot(sep_x, sep_y, linewidth=line_width * 3, color=color_line) `

**Comment by rsameni** [comment]
These are lead separator ticks, which exist on standard ECG images; but they shouldn't be as tall as in the example you provided. Please try the latest updates of the code. If the ticks are still as tall as shown in the image, please share the command-line parameters used to generate your example. Thank you!

**Comment by matthewreyna** [comment]
The tall lead separator ticks were caused by a bug in the ECG image generation code. Commit [27b90f5](https://github.com/alphanumericslab/ecg-image-kit/commit/27b90f56896c9fc78b05a83ca14844ea2637aa0b) fixes this bug.
