### ISSUE TITLE
Default values for some parameters of the function get_paper_ecg are not correct.

### ISSUE THREAD

**Issue by wenh06** [alphanumericslab/ecg-image-kit#5]
The function [`get_paper_ecg`](https://github.com/alphanumericslab/ecg-image-kit/blob/1ab758b0d1d4e2497bd9ba40a158aa2029265b4f/codes/ecg-image-generator/extract_leads.py#L20) has some incorrect default values for some of the parameters:

`add_dc_pulse`, `add_bw`, `show_grid`, `add_print` have boolean default values `True`, but in [the following code](https://github.com/alphanumericslab/ecg-image-kit/blob/1ab758b0d1d4e2497bd9ba40a158aa2029265b4f/codes/ecg-image-generator/extract_leads.py#L138-L142)

```python
    for i in range(len(ecg_frame)):
        dc = add_dc_pulse.rvs()
        bw = add_bw.rvs()
        grid = show_grid.rvs()
        print_txt = add_print.rvs()
```

they should be some scipy distributions.

`standard_colours` has default value `True`, which would result in `KeyError: 'colourTrue'` in the [`ecg_plot`](https://github.com/alphanumericslab/ecg-image-kit/blob/1ab758b0d1d4e2497bd9ba40a158aa2029265b4f/codes/ecg-image-generator/ecg_plot.py#L67) since `True > 0` is True in [the following code](https://github.com/alphanumericslab/ecg-image-kit/blob/1ab758b0d1d4e2497bd9ba40a158aa2029265b4f/codes/ecg-image-generator/ecg_plot.py#L187-L193):

```python
    elif(standard_colours > 0):
        random_colour_index = standard_colours
        color_major = standard_major_colors['colour'+str(random_colour_index)]
        color_minor = standard_minor_colors['colour'+str(random_colour_index)]
```

**Comment by deepanshi-s** [comment]
Changed default values.

**Comment by rsameni** [comment]
Good catch! Thank you Wen.
