### ISSUE TITLE
Why wfdb.wrsamp when generate .png images?

### ISSUE THREAD

**Issue by sikicode** [alphanumericslab/ecg-image-kit#8]
I used the given image generator to generate PNG image files from WFDB files. 
I noticed that along with generated PNGs, the tool also generate new WFDB files, and these newly generated binaries and headers are not the same as input WFDB files. Is there any reason that the code is designed in this way?

**Comment by matthewreyna** [comment]
The ECG image does not show the entire ECG signal, so the image generator code creates new WFDB files that only contain the parts of the signal that it plots in the ECG image. It replaces the unplotted parts of the signal with NaN values.

For example, for 12-lead ECG with a 10-second duration, the code will generate, by default,
(1) a grid with 4 columns and 3 rows that shows 2.5 seconds of signal for each lead, where the left-most column has the first 2.5 seconds of the signal for its 3 leads, the second-to-left-most column has the next 2.5 seconds of the signal for its 3 leads, and so on; and
(2) a long strip with 1 column and 1 row that shows the entire 10 seconds of the signal for 1 lead, where the time in the long strip aligns with the times in the grid.

If this is unclear, or if you change the default settings, then you can always check the plotted parts of the signal by inspecting the WFDB files that the image generation code creates.
